name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm i
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_MAX_TABLE_ROWS: 100
          envkey_NODE_ENV: "production"
          envkey_PAGE_SIZE: 4096
      - run: pnpm lint
      - run: pnpm format
      - run: pnpm test
      - run: pnpm build
        env:
          CI: true
