name: Build and Deploy Docs Site
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install and Build
        run: |
          pnpm i
          pnpm dlx typedoc --out docs --entryPointStrategy expand ./src/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
